[package]
name = "rvld"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
static_assertions = "1.1"
# TODO: this crate is outdated on crates.io
zero = "0.1.2"
bitflags = "1.3.2"
